package rabbitmq

import (
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/lerity-yao/czt-contrib/cztctl/api/gogen"
	"github.com/lerity-yao/czt-contrib/cztctl/api/spec"
	"github.com/lerity-yao/czt-contrib/cztctl/config"
	"github.com/lerity-yao/czt-contrib/cztctl/internal/version"
	"github.com/lerity-yao/czt-contrib/cztctl/util/format"
	"github.com/lerity-yao/czt-contrib/cztctl/util/pathx"
	"github.com/lerity-yao/czt-contrib/cztctl/vars"
)

const (
	listenerFilename = "listeners"
	listenerTemplate = `// Code generated by cztctl. DO NOT EDIT.
// cztctl {{.version}}

package handler

import (
	{{.ImportPackages}}
)

func RegisterHandlers(server *service.ServiceGroup, serverCtx *svc.ServiceContext) {
	{{.ListenerAdditions}}
}
`
)

func genListener(dir, rootPkg string, cfg *config.Config, api *spec.ApiSpec) error {
	listenerFileName, err := format.FileNamingFormat(cfg.NamingFormat, listenerFilename)
	if err != nil {
		return err
	}

	listenerFileName = listenerFileName + ".go"
	filename := path.Join(dir, handlerDir, listenerFileName)
	_ = os.Remove(filename)

	listenerAdditionNames := getListenerAdditions(api)
	imports := getListenerImports(api, rootPkg)

	return gogen.GenFile(gogen.FileGenConfig{
		Dir:             dir,
		Subdir:          handlerDir,
		Filename:        listenerFileName,
		TemplateName:    "listenerTemplate",
		Category:        category,
		TemplateFile:    listenerTemplateFile,
		BuiltinTemplate: listenerTemplate,
		Data: map[string]any{
			"ImportPackages":    strings.Join(imports, "\n"),
			"ListenerAdditions": strings.Join(listenerAdditionNames, "\n"),
			"version":           version.BuildVersion,
		},
	})
}

func getListenerImports(api *spec.ApiSpec, parentPkg string) []string {
	importSet := make(map[string]struct{})
	var importNames []string
	addImport := func(s string) {
		if _, ok := importSet[s]; !ok {
			importSet[s] = struct{}{}
			importNames = append(importNames, s)
		}
	}

	addImport(fmt.Sprintf("\"%s%s\"", vars.ProjectOpenSourceURL, "/core/service"))
	addImport(fmt.Sprintf("\"%s\"", pathx.JoinPackages(parentPkg, contextDir)))

	for _, g := range api.Service.Groups {
		for _, h := range g.Routes {
			handlerPath := getHandlerFolderPath(g, h)
			pkgName := handlerPath[strings.LastIndex(handlerPath, "/")+1:]
			addImport(fmt.Sprintf("\"%s\"", pathx.JoinPackages(parentPkg, handlerDir, pkgName)))
		}
	}

	return importNames
}

func getListenerAdditions(api *spec.ApiSpec) []string {
	seen := make(map[string]struct{})
	var listenerAdditionNames []string
	for _, g := range api.Service.Groups {
		for _, h := range g.Routes {
			handler := getHandlerName(h)
			handlerPath := getHandlerFolderPath(g, h)
			pkgName := handlerPath[strings.LastIndex(handlerPath, "/")+1:]
			if handlerPath != handlerDir {
				handler = strings.Title(handler)
			}

			l := fmt.Sprintf("server.Add(%s.%s(serverCtx))",
				pkgName, handler)
			if _, ok := seen[l]; !ok {
				seen[l] = struct{}{}
				listenerAdditionNames = append(listenerAdditionNames, l)
			}
		}
	}

	return listenerAdditionNames
}
