package cron

import (
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/lerity-yao/czt-contrib/cztctl/api/gogen"
	"github.com/lerity-yao/czt-contrib/cztctl/api/spec"
	"github.com/lerity-yao/czt-contrib/cztctl/config"
	"github.com/lerity-yao/czt-contrib/cztctl/internal/version"
	"github.com/lerity-yao/czt-contrib/cztctl/util/format"
	"github.com/lerity-yao/czt-contrib/cztctl/util/pathx"
	"github.com/lerity-yao/czt-contrib/cztctl/vars"
)

const (
	workerFilename = "workers"
	workerTemplate = `// Code generated by cztctl. DO NOT EDIT.
// cztctl {{.version}}

package handler

import (
	{{.ImportPackages}}
)

func RegisterHandlers(server *service.ServiceGroup, serverCtx *svc.ServiceContext) {
	{{.WorkerAdditions}}
}
`
)

func genWorker(dir, rootPkg string, cfg *config.Config, api *spec.ApiSpec) error {
	workerFileName, err := format.FileNamingFormat(cfg.NamingFormat, workerFilename)
	if err != nil {
		return err
	}

	workerFileName = workerFileName + ".go"
	filename := path.Join(dir, handlerDir, workerFileName)
	_ = os.Remove(filename)

	workerAdditionNames := getWorkerAdditions(api)
	imports := workerImports(api, rootPkg)

	return gogen.GenFile(gogen.FileGenConfig{
		Dir:             dir,
		Subdir:          handlerDir,
		Filename:        workerFileName,
		TemplateName:    "workerTemplate",
		Category:        category,
		TemplateFile:    workerTemplateFile,
		BuiltinTemplate: workerTemplate,
		Data: map[string]any{
			"ImportPackages":  strings.Join(imports, "\n"),
			"WorkerAdditions": strings.Join(workerAdditionNames, "\n"),
			"version":         version.BuildVersion,
		},
	})
}

func workerImports(api *spec.ApiSpec, parentPkg string) []string {
	importSet := make(map[string]struct{})
	var importNames []string
	addImport := func(s string) {
		if _, ok := importSet[s]; !ok {
			importSet[s] = struct{}{}
			importNames = append(importNames, s)
		}
	}

	addImport(fmt.Sprintf("\"%s%s\"", vars.ProjectOpenSourceURL, "/core/service"))
	addImport(fmt.Sprintf("\"%s\"", pathx.JoinPackages(parentPkg, contextDir)))

	hasCron := false
	for _, g := range api.Service.Groups {
		for _, h := range g.Routes {
			handlerPath := getHandlerFolderPath(g, h)
			pkgName := handlerPath[strings.LastIndex(handlerPath, "/")+1:]
			addImport(fmt.Sprintf("\"%s\"", pathx.JoinPackages(parentPkg, handlerDir, pkgName)))
			if h.Cron != "" {
				hasCron = true
			}
		}
	}
	if hasCron {
		// time 用于 go-zero RestConf.Timeout (ms) 转 time.Duration
		addImport("\"time\"")
		addImport(fmt.Sprintf("\"%s\"", "github.com/hibiken/asynq"))
	}

	return importNames
}

func getWorkerAdditions(api *spec.ApiSpec) []string {
	var workerAdditionNames []string
	seen := make(map[string]struct{})
	hasCron := false
	for _, g := range api.Service.Groups {
		for _, h := range g.Routes {
			if h.Cron != "" {
				hasCron = true
				break
			}
		}
		if hasCron {
			break
		}
	}
	if hasCron {
		// 多个定时任务共享同一个 Timeout（go-zero RestConf.Timeout 接管），
		// MaxRetry 依然保留 per-task 配置能力
		workerAdditionNames = append(workerAdditionNames,
			"timeoutOpt := asynq.Timeout(time.Duration(serverCtx.Config.Timeout) * time.Millisecond)")
	}
	for _, g := range api.Service.Groups {
		for _, h := range g.Routes {
			pattern, _ := getHandlerBaseName(h)
			handler := getHandlerName(h)
			handlerPath := getHandlerFolderPath(g, h)
			pkgName := handlerPath[strings.LastIndex(handlerPath, "/")+1:]
			if handlerPath != handlerDir {
				handler = strings.Title(handler)
			}

			if h.Cron != "" {
				// 定时任务：CronAdd 内部已注册 handler，不再重复调 Add
				// 超时接管于 go-zero RestConf.Timeout，与 v0.1.0+ cron 模块推荐用法对齐
				cronLine := fmt.Sprintf("serverCtx.CronServer.CronAdd(\"%s\", \"%s\",\n\t\t%s.%s(serverCtx),\n\t\ttimeoutOpt,\n\t\tasynq.MaxRetry(%d))",
					h.Cron, pattern, pkgName, handler, h.CronRetry)
				if _, ok := seen[cronLine]; !ok {
					seen[cronLine] = struct{}{}
					workerAdditionNames = append(workerAdditionNames, cronLine)
				}
			} else {
				// 非定时任务（外部投递消费端）：仅注册 handler
				addLine := fmt.Sprintf("serverCtx.CronServer.Add(\"%s\", %s.%s(serverCtx))",
					pattern, pkgName, handler)
				if _, ok := seen[addLine]; !ok {
					seen[addLine] = struct{}{}
					workerAdditionNames = append(workerAdditionNames, addLine)
				}
			}
		}
	}
	workerAdditionNames = append(workerAdditionNames, "server.Add(serverCtx.CronServer)")

	return workerAdditionNames
}
