package cron

import (
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/lerity-yao/czt-contrib/cztctl/api/gogen"
	"github.com/lerity-yao/czt-contrib/cztctl/api/spec"
	"github.com/lerity-yao/czt-contrib/cztctl/config"
	"github.com/lerity-yao/czt-contrib/cztctl/internal/version"
	"github.com/lerity-yao/czt-contrib/cztctl/util/format"
	"github.com/lerity-yao/czt-contrib/cztctl/util/pathx"
	"github.com/lerity-yao/czt-contrib/cztctl/vars"
)

const (
	workerFilename = "workers"
	workerTemplate = `// Code generated by cztctl. DO NOT EDIT.
// cztctl {{.version}}

package handler

import (
	{{.ImportPackages}}
)

func RegisterHandlers(server *service.ServiceGroup, serverCtx *svc.ServiceContext) {
	{{.WorkerAdditions}}
}
`
)

func genWorker(dir, rootPkg string, cfg *config.Config, api *spec.ApiSpec) error {
	workerFileName, err := format.FileNamingFormat(cfg.NamingFormat, workerFilename)
	if err != nil {
		return err
	}

	workerFileName = workerFileName + ".go"
	filename := path.Join(dir, handlerDir, workerFileName)
	_ = os.Remove(filename)

	workerAdditionNames := getWorkerAdditions(api)
	imports := workerImports(api, rootPkg)

	return gogen.GenFile(gogen.FileGenConfig{
		Dir:             dir,
		Subdir:          handlerDir,
		Filename:        workerFileName,
		TemplateName:    "workerTemplate",
		Category:        category,
		TemplateFile:    workerTemplateFile,
		BuiltinTemplate: workerTemplate,
		Data: map[string]any{
			"ImportPackages":  strings.Join(imports, "\n"),
			"WorkerAdditions": strings.Join(workerAdditionNames, "\n"),
			"version":         version.BuildVersion,
		},
	})
}

func workerImports(api *spec.ApiSpec, parentPkg string) []string {
	importSet := make(map[string]struct{})
	var importNames []string
	addImport := func(s string) {
		if _, ok := importSet[s]; !ok {
			importSet[s] = struct{}{}
			importNames = append(importNames, s)
		}
	}

	addImport(fmt.Sprintf("\"%s%s\"", vars.ProjectOpenSourceURL, "/core/service"))
	addImport(fmt.Sprintf("\"%s\"", pathx.JoinPackages(parentPkg, contextDir)))

	for _, g := range api.Service.Groups {
		for _, h := range g.Routes {
			handlerPath := getHandlerFolderPath(g, h)
			pkgName := handlerPath[strings.LastIndex(handlerPath, "/")+1:]
			addImport(fmt.Sprintf("\"%s\"", pathx.JoinPackages(parentPkg, handlerDir, pkgName)))
			if h.Cron != "" {
				addImport(fmt.Sprintf("\"%s\"", "github.com/hibiken/asynq"))
			}
		}
	}

	return importNames
}

func getWorkerAdditions(api *spec.ApiSpec) []string {
	var workerAdditionNames []string
	seen := make(map[string]struct{})
	for _, g := range api.Service.Groups {
		for _, h := range g.Routes {
			pattern, _ := getHandlerBaseName(h)
			handler := getHandlerName(h)
			handlerPath := getHandlerFolderPath(g, h)
			pkgName := handlerPath[strings.LastIndex(handlerPath, "/")+1:]
			if handlerPath != handlerDir {
				handler = strings.Title(handler)
			}

			var l string
			if h.Cron != "" {
				retry := h.CronRetry
				l = fmt.Sprintf("serverCtx.CronServer.CronAdd(\"%s\", \"%s\", %s.%s(serverCtx), asynq.MaxRetry(%d))",
					h.Cron, pattern, pkgName, handler, retry)
			} else {
				l = fmt.Sprintf("serverCtx.CronServer.Add(\"%s\", %s.%s(serverCtx))",
					pattern, pkgName, handler)
			}
			if _, ok := seen[l]; !ok {
				seen[l] = struct{}{}
				workerAdditionNames = append(workerAdditionNames, l)
			}
		}
	}
	workerAdditionNames = append(workerAdditionNames, "server.Add(serverCtx.CronServer)")

	return workerAdditionNames
}
