// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.4.2

package types

type Job struct {
	Id int `json:"id"`
}

type Name struct {
	Code int `json:"code"`
}

type User struct {
	Name string `json:"name"` // 用户名称
}
