// Code generated by cztctl. DO NOT EDIT.
// cztctl 1.9.4.2

package handler

import (
	"example/example/internal/handler/demoA"
	"example/example/internal/svc"
	"github.com/zeromicro/go-zero/core/service"
)

func RegisterHandlers(server *service.ServiceGroup, serverCtx *svc.ServiceContext) {
	serverCtx.CronServer.CronAdd("*/1 * * * *", "GDemoB")
	serverCtx.CronServer.Add("GDemoA", demoA.GDemoAHandler(serverCtx))
	server.Add(serverCtx.CronServer)
	serverCtx.CronServer.Add("GDemoB", demoA.GDemoBHandler(serverCtx))
}
