// Code generated by cztctl. DO NOT EDIT.
// cztctl 1.9.4.2

package handler

import (
	"context"
	"example/example/internal/handler/demoA"
	"example/example/internal/svc"
	"github.com/zeromicro/go-zero/core/service"
)

func RegisterHandlers(server *service.ServiceGroup, serverCtx *svc.ServiceContext) {
	ctx := context.Background()
	server.Add(demoA.GDemoAHandler(ctx, serverCtx))
	server.Add(demoA.GDemoBHandler(ctx, serverCtx))
}
