// Code generated by cztctl. DO NOT EDIT.
// cztctl 1.9.4.2

package handler

import (
	"github.com/lerity-yao/czt-contrib/mq/rabbitmq/example/internal/handler/demoA"
	"github.com/lerity-yao/czt-contrib/mq/rabbitmq/example/internal/svc"
	"github.com/zeromicro/go-zero/core/service"
)

func RegisterHandlers(server *service.ServiceGroup, serverCtx *svc.ServiceContext) {
	server.Add(demoA.GDemoAHandler(serverCtx))
	server.Add(demoA.GDemoBHandler(serverCtx))
}
